selftests/powerpc: Suppress false positive -Wmaybe-uninitialized with GCC 15
GCC 15 reports the below false positive '-Wmaybe-uninitialized' warning
in vphn_unpack_associativity() when building the powerpc selftests.

  # make -C tools/testing/selftests TARGETS="powerpc"
  [...]
    CC       test-vphn
  In file included from test-vphn.c:3:
  In function ‘vphn_unpack_associativity’,
      inlined from ‘test_one’ at test-vphn.c:371:2,
      inlined from ‘test_vphn’ at test-vphn.c:399:9:
  test-vphn.c:10:33: error: ‘be_packed’ may be used uninitialized [-Werror=maybe-uninitialized]
     10 | #define be16_to_cpup(x)         bswap_16(*x)
        |                                 ^~~~~~~~
  vphn.c:42:27: note: in expansion of macro ‘be16_to_cpup’
     42 |                 u16 new = be16_to_cpup(field++);
        |                           ^~~~~~~~~~~~
  In file included from test-vphn.c:19:
  vphn.c: In function ‘test_vphn’:
  vphn.c:27:16: note: ‘be_packed’ declared here
     27 |         __be64 be_packed[VPHN_REGISTER_COUNT];
        |                ^~~~~~~~~
  cc1: all warnings being treated as errors

When vphn_unpack_associativity() is called from hcall_vphn(), this error
is not seen during compilation because GCC 15 seems to consider 'retbuf'
always populated from the hypervisor which is eventually referred by
'be_packed'. However, GCC 15's dataflow analysis can’t prove the same
before the first dereference when vphn_unpack_associativity() is called
from test_one() with pre-initialized array of 'struct test'. This
results in a false positive warning which is promoted to an error under
'-Werror'. This problem is not seen when the compilation is performed
with GCC 13 and 14.

Suppress the warning locally around the offending statement when
building with GCC 15 using a diagnostic pragma. This keeps the build
working while limiting the scope of the suppression to the specific
statement that triggers the false positive. An issue [1] has also been
created on GCC bugzilla.

[1] https://gcc.gnu.org/bugzilla/show_bug.cgi?id=124427

Fixes: 58dae82843f5 ("selftests/powerpc: Add test for VPHN")
Reviewed-by: Vaibhav Jain <vaibhav@linux.ibm.com>
Signed-off-by: Amit Machhiwal <amachhiw@linux.ibm.com>